-- A* Search
UPDATE algorithms SET 
code_cpp = 'void aStarSearch(int grid[][COL], Pair src, Pair dest) {\n    if (isValid(src.first, src.second) == false) return;\n    if (isUnBlocked(grid, src.first, src.second) == false) return;\n    if (isDestination(src.first, src.second, dest)) return;\n    bool closedList[ROW][COL];\n    memset(closedList, false, sizeof(closedList));\n    cell cellDetails[ROW][COL];\n    // Initialize start node and open list\n    // Loop until open list is empty\n    // Extract min f, update neighbors\n}',
code_java = 'void aStarSearch(int grid[][], int[] src, int[] dest) {\n    if (!isValid(src[0], src[1])) return;\n    if (!isUnBlocked(grid, src[0], src[1])) return;\n    if (isDestination(src[0], src[1], dest)) return;\n    boolean[][] closedList = new boolean[ROW][COL];\n    Cell[][] cellDetails = new Cell[ROW][COL];\n    // Initialize start node and open list\n    // Loop until open list is empty\n    // Extract min f, update neighbors\n}',
code_python = 'def aStarSearch(grid, src, dest):\n    if not isValid(src[0], src[1]): return\n    if not isUnBlocked(grid, src[0], src[1]): return\n    if isDestination(src[0], src[1], dest): return\n    closedList = [[False for _ in range(COL)] for _ in range(ROW)]\n    cellDetails = [[Cell() for _ in range(COL)] for _ in range(ROW)]\n    # Initialize start node and open list\n    # Loop until open list is empty\n    # Extract min f, update neighbors'
WHERE id = 'aStar';

-- Dijkstra's
UPDATE algorithms SET 
code_cpp = 'void dijkstra(int graph[V][V], int src) {\n    int dist[V];\n    bool sptSet[V];\n    for (int i = 0; i < V; i++) dist[i] = INT_MAX, sptSet[i] = false;\n    dist[src] = 0;\n    for (int count = 0; count < V - 1; count++) {\n        int u = minDistance(dist, sptSet);\n        sptSet[u] = true;\n        for (int v = 0; v < V; v++)\n            if (!sptSet[v] && graph[u][v] && dist[u] != INT_MAX && dist[u] + graph[u][v] < dist[v])\n                dist[v] = dist[u] + graph[u][v];\n    }\n}',
code_java = 'void dijkstra(int graph[][], int src) {\n    int dist[] = new int[V];\n    Boolean sptSet[] = new Boolean[V];\n    for (int i = 0; i < V; i++) {\n        dist[i] = Integer.MAX_VALUE;\n        sptSet[i] = false;\n    }\n    dist[src] = 0;\n    for (int count = 0; count < V - 1; count++) {\n        int u = minDistance(dist, sptSet);\n        sptSet[u] = true;\n        for (int v = 0; v < V; v++)\n            if (!sptSet[v] && graph[u][v] != 0 && dist[u] != Integer.MAX_VALUE && dist[u] + graph[u][v] < dist[v])\n                dist[v] = dist[u] + graph[u][v];\n    }\n}',
code_python = 'def dijkstra(graph, src):\n    dist = [float("inf")] * V\n    sptSet = [False] * V\n    dist[src] = 0\n    for cout in range(V):\n        u = minDistance(dist, sptSet)\n        sptSet[u] = True\n        for v in range(V):\n            if graph[u][v] > 0 and sptSet[v] == False and dist[v] > dist[u] + graph[u][v]:\n                dist[v] = dist[u] + graph[u][v]'
WHERE id = 'dijkstras';

-- Kahn's
UPDATE algorithms SET
code_cpp = 'void topologicalSort(vector<int> adj[], int V) {\n    vector<int> in_degree(V, 0);\n    for (int u = 0; u < V; u++) {\n        for (auto itr = adj[u].begin(); itr != adj[u].end(); itr++)\n            in_degree[*itr]++;\n    }\n    queue<int> q;\n    for (int i = 0; i < V; i++) {\n        if (in_degree[i] == 0) q.push(i);\n    }\n    int cnt = 0;\n    vector<int> top_order;\n    while (!q.empty()) {\n        int u = q.front(); q.pop();\n        top_order.push_back(u);\n        for (auto itr = adj[u].begin(); itr != adj[u].end(); itr++) {\n            if (--in_degree[*itr] == 0) q.push(*itr);\n        }\n        cnt++;\n    }\n}',
code_java = 'void topologicalSort(List<List<Integer>> adj, int V) {\n    int[] in_degree = new int[V];\n    for (int u = 0; u < V; u++) {\n        for (int node : adj.get(u)) in_degree[node]++;\n    }\n    Queue<Integer> q = new LinkedList<>();\n    for (int i = 0; i < V; i++) {\n        if (in_degree[i] == 0) q.add(i);\n    }\n    List<Integer> topOrder = new ArrayList<>();\n    while (!q.isEmpty()) {\n        int u = q.poll();\n        topOrder.add(u);\n        for (int node : adj.get(u)) {\n            if (--in_degree[node] == 0) q.add(node);\n        }\n    }\n}',
code_python = 'def topologicalSort(adj, V):\n    in_degree = [0]*(V)\n    for i in range(V):\n        for j in adj[i]: in_degree[j] += 1\n    queue = []\n    for i in range(V):\n        if in_degree[i] == 0: queue.append(i)\n    top_order = []\n    while queue:\n        u = queue.pop(0)\n        top_order.append(u)\n        for i in adj[u]:\n            in_degree[i] -= 1\n            if in_degree[i] == 0: queue.append(i)'
WHERE id = 'kahns';

-- Bellman-Ford
UPDATE algorithms SET
code_cpp = 'void BellmanFord(struct Graph* graph, int src) {\n    int V = graph->V, E = graph->E;\n    int dist[V];\n    for (int i = 0; i < V; i++) dist[i] = INT_MAX;\n    dist[src] = 0;\n    for (int i = 1; i <= V - 1; i++) {\n        for (int j = 0; j < E; j++) {\n            int u = graph->edge[j].src, v = graph->edge[j].dest, weight = graph->edge[j].weight;\n            if (dist[u] != INT_MAX && dist[u] + weight < dist[v]) dist[v] = dist[u] + weight;\n        }\n    }\n}',
code_java = 'void BellmanFord(Graph graph, int src) {\n    int V = graph.V, E = graph.E;\n    int dist[] = new int[V];\n    for (int i = 0; i < V; ++i) dist[i] = Integer.MAX_VALUE;\n    dist[src] = 0;\n    for (int i = 1; i < V; ++i) {\n        for (int j = 0; j < E; ++j) {\n            int u = graph.edge[j].src, v = graph.edge[j].dest, weight = graph.edge[j].weight;\n            if (dist[u] != Integer.MAX_VALUE && dist[u] + weight < dist[v]) dist[v] = dist[u] + weight;\n        }\n    }\n}',
code_python = 'def BellmanFord(graph, src):\n    dist = [float("Inf")] * V\n    dist[src] = 0\n    for _ in range(V - 1):\n        for u, v, w in graph:\n            if dist[u] != float("Inf") and dist[u] + w < dist[v]:\n                dist[v] = dist[u] + w'
WHERE id = 'bellmanFord';

-- Prim's
UPDATE algorithms SET
code_cpp = 'void primMST(int graph[V][V]) {\n    int parent[V], key[V];\n    bool mstSet[V];\n    for (int i = 0; i < V; i++) key[i] = INT_MAX, mstSet[i] = false;\n    key[0] = 0;\n    parent[0] = -1;\n    for (int count = 0; count < V - 1; count++) {\n        int u = minKey(key, mstSet);\n        mstSet[u] = true;\n        for (int v = 0; v < V; v++)\n            if (graph[u][v] && mstSet[v] == false && graph[u][v] < key[v])\n                parent[v] = u, key[v] = graph[u][v];\n    }\n}',
code_java = 'void primMST(int graph[][]) {\n    int parent[] = new int[V], key[] = new int[V];\n    Boolean mstSet[] = new Boolean[V];\n    for (int i = 0; i < V; i++) { key[i] = Integer.MAX_VALUE; mstSet[i] = false; }\n    key[0] = 0; parent[0] = -1;\n    for (int count = 0; count < V - 1; count++) {\n        int u = minKey(key, mstSet);\n        mstSet[u] = true;\n        for (int v = 0; v < V; v++)\n            if (graph[u][v] != 0 && mstSet[v] == false && graph[u][v] < key[v]) {\n                parent[v] = u;\n                key[v] = graph[u][v];\n            }\n    }\n}',
code_python = 'def primMST(graph):\n    key = [float("inf")] * V\n    parent = [None] * V\n    mstSet = [False] * V\n    key[0] = 0\n    parent[0] = -1\n    for cout in range(V):\n        u = minKey(key, mstSet)\n        mstSet[u] = True\n        for v in range(V):\n            if graph[u][v] > 0 and mstSet[v] == False and key[v] > graph[u][v]:\n                key[v] = graph[u][v]\n                parent[v] = u'
WHERE id = 'prims';

-- Kruskal's
UPDATE algorithms SET
code_cpp = 'void KruskalMST(Graph* graph) {\n    int V = graph->V; Edge result[V];\n    int e = 0, i = 0;\n    qsort(graph->edge, graph->E, sizeof(graph->edge[0]), myComp);\n    subset* subsets = new subset[(V * sizeof(subset))];\n    for (int v = 0; v < V; ++v) { subsets[v].parent = v; subsets[v].rank = 0; }\n    while (e < V - 1 && i < graph->E) {\n        Edge next_edge = graph->edge[i++];\n        int x = find(subsets, next_edge.src), y = find(subsets, next_edge.dest);\n        if (x != y) {\n            result[e++] = next_edge;\n            Union(subsets, x, y);\n        }\n    }\n}',
code_java = 'void KruskalMST() {\n    Edge result[] = new Edge[V];\n    int e = 0, i = 0;\n    for (i = 0; i < V; ++i) result[i] = new Edge();\n    Arrays.sort(edge);\n    subset subsets[] = new subset[V];\n    for (i = 0; i < V; ++i) subsets[i] = new subset(i, 0);\n    i = 0;\n    while (e < V - 1) {\n        Edge next_edge = edge[i++];\n        int x = find(subsets, next_edge.src), y = find(subsets, next_edge.dest);\n        if (x != y) {\n            result[e++] = next_edge;\n            Union(subsets, x, y);\n        }\n    }\n}',
code_python = 'def KruskalMST(self):\n    result = []\n    i, e = 0, 0\n    self.graph = sorted(self.graph, key=lambda item: item[2])\n    parent = []\n    rank = []\n    for node in range(self.V):\n        parent.append(node)\n        rank.append(0)\n    while e < self.V - 1:\n        u, v, w = self.graph[i]\n        i = i + 1\n        x = self.find(parent, u)\n        y = self.find(parent, v)\n        if x != y:\n            e = e + 1\n            result.append([u, v, w])\n            self.union(parent, rank, x, y)'
WHERE id = 'kruskals';

-- Tarjan's
UPDATE algorithms SET
code_cpp = 'void SCCUtil(int u, int disc[], int low[], stack<int>* st, bool stackMember[]) {\n    static int time = 0;\n    disc[u] = low[u] = ++time;\n    st->push(u);\n    stackMember[u] = true;\n    for (int v : adj[u]) {\n        if (disc[v] == -1) {\n            SCCUtil(v, disc, low, st, stackMember);\n            low[u] = min(low[u], low[v]);\n        } else if (stackMember[v] == true) {\n            low[u] = min(low[u], disc[v]);\n        }\n    }\n    int w = 0;\n    if (low[u] == disc[u]) {\n        while (st->top() != u) {\n            w = (int)st->top(); st->pop(); stackMember[w] = false;\n        }\n        w = (int)st->top(); st->pop(); stackMember[w] = false;\n    }\n}',
code_java = 'void SCCUtil(int u, int low[], int disc[], boolean stackMember[], Stack<Integer> st) {\n    disc[u] = time; low[u] = time; time++;\n    stackMember[u] = true;\n    st.push(u);\n    for (int v : adj[u]) {\n        if (disc[v] == -1) {\n            SCCUtil(v, low, disc, stackMember, st);\n            low[u] = Math.min(low[u], low[v]);\n        } else if (stackMember[v]) {\n            low[u] = Math.min(low[u], disc[v]);\n        }\n    }\n    int w = -1;\n    if (low[u] == disc[u]) {\n        while (w != u) {\n            w = (int)st.pop();\n            stackMember[w] = false;\n        }\n    }\n}',
code_python = 'def SCCUtil(self, u, low, disc, stackMember, st):\n    disc[u] = self.Time\n    low[u] = self.Time\n    self.Time += 1\n    stackMember[u] = True\n    st.append(u)\n    for v in self.graph[u]:\n        if disc[v] == -1:\n            self.SCCUtil(v, low, disc, stackMember, st)\n            low[u] = min(low[u], low[v])\n        elif stackMember[v]:\n            low[u] = min(low[u], disc[v])\n    w = -1\n    if low[u] == disc[u]:\n        while w != u:\n            w = st.pop()\n            stackMember[w] = False'
WHERE id = 'tarjans';
